---
title: "lab9"
author: "Oladele A. OLUWAYIOSE"
date: "4/26/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(lubridate)
```

##prepping datasets
```{r}
report_03_11_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-11-2020.csv")) %>%
  rename(Country_Region = "Country/Region", Province_State = "Province/State")

##confirmed cases
time_series_confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")

time_series_confirmed_long <- time_series_confirmed %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
               names_to = "Date", values_to = "Confirmed") 

##number of deaths
time_series_deaths <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")

time_series_deaths_long <- time_series_deaths %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
               names_to = "Date", values_to = "Deaths")
head(time_series_deaths_long)

##merging datasets
time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
head(time_series_confirmed_long)

time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)

time_series_long_joined <- full_join(time_series_confirmed_long,
                                     time_series_deaths_long, by = c("Key"))

head(time_series_long_joined)
which(is.na(time_series_long_joined$Confirmed))
which(is.na(time_series_long_joined$Deaths))

###recovered data
### download the file
time_series_recovered <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")

### convert to long format
time_series_recovered_long <- time_series_recovered %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
               names_to = "Date", values_to = "Recovered")

### Create the Key
time_series_recovered_long <- time_series_recovered_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Recovered)

### Merge with prior table (only this time will delete the Key column
### because we have no further use for it)
time_series_long_joined <- full_join(time_series_long_joined,
                                     time_series_recovered_long, by = c("Key")) %>% 
  select(-Key)
head(time_series_long_joined)

##reformarting data
time_series_long_joined$Date <- mdy(time_series_long_joined$Date)

time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")
head(time_series_long_joined_counts)
```

##plotting
```{r}
##US plotting
# time_series_long_joined %>% 
#   group_by(Country_Region,Date) %>% 
#   summarise_at(c("Confirmed", "Deaths", "Recovered"), sum) %>% 
#   filter (Country_Region == "US") %>% 
#   ggplot(aes(x = Date,  y = Confirmed)) + 
#   geom_point() +
#   geom_line() +
#   ggtitle("US Confirmed COVID-19 Cases")
##nigeria plotting

time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths", "Recovered"), sum) %>% 
  filter (Country_Region == "Nigeria") %>% 
  ggplot(aes(x = Date,  y = Confirmed)) + 
  geom_point() +
  geom_line() +
  ggtitle("Nigeria Confirmed COVID-19 Cases")

time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths", "Recovered"), sum) %>% 
  filter (Country_Region == "Nigeria") %>% 
  ggplot(aes(x = Date,  y = Confirmed)) + 
  geom_point() +
  geom_line() +
  ggtitle("Nigeria COVID-19 related death")
```


```{r}
# time_series_long_joined %>% 
#   group_by(Country_Region,Date) %>% 
#   summarise_at(c("Confirmed", "Deaths", "Recovered"), sum) %>% 
#   filter (Country_Region %in% c("China","Japan", "Korea, South",
#                                 "Italy","Spain", "US")) %>% 
#   ggplot(aes(x = Date,  y = Confirmed)) + 
#   geom_point() +
#   geom_line() +
#   ggtitle("Confirmed COVID-19 Cases") +
#   facet_wrap(~Country_Region, ncol=2, scales="free_y")

time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths", "Recovered"), sum) %>% 
  filter (Country_Region %in% c("China","US", "Nigeria", "Ghana",
                                "South Africa","Cameroon")) %>% 
  ggplot(aes(x = Date,  y = Confirmed)) + 
  geom_point() +
  geom_line() +
  ggtitle("Confirmed COVID-19 Cases") +
  facet_wrap(~Country_Region, ncol=2, scales="free_y")

time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths", "Recovered"), sum) %>% 
  filter (Country_Region %in% c("China","US", "Nigeria", "Ghana",
                                "South Africa","Cameroon")) %>% 
  ggplot(aes(x = Date,  y = Deaths)) + 
  geom_point() +
  geom_line() +
  ggtitle("Number of COVID-19 related deaths") +
  facet_wrap(~Country_Region, ncol=2, scales="free_y")


# time_series_long_joined %>% 
#   group_by(Country_Region,Date) %>% 
#   summarise_at(c("Confirmed", "Deaths", "Recovered"), sum) %>% 
#   filter (Country_Region %in% c("China","France","Italy", 
#                                 "Korea, South", "US")) %>% 
#   ggplot(aes(x = Date,  y = Confirmed, color = Country_Region)) + 
#   geom_point() +
#   geom_line() +
#   ggtitle("Confirmed COVID-19 Cases")

time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths", "Recovered"), sum) %>% 
  filter (Country_Region %in% c("China","US", "Nigeria", "Ghana",
                                "South Africa","Cameroon")) %>% 
  ggplot(aes(x = Date,  y = Confirmed, color = Country_Region)) + 
  geom_point() +
  geom_line() +
  ggtitle("Confirmed COVID-19 Cases")

time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths", "Recovered"), sum) %>% 
  filter (Country_Region %in% c("China","US", "Nigeria", "Ghana",
                                "South Africa","Cameroon")) %>% 
  ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
  geom_point() +
  geom_line() +
  ggtitle("Number of COVID-19 related deaths")


# time_series_long_joined_counts %>% 
#   group_by(Country_Region, Report_Type, Date) %>% 
#   summarise(Counts = sum(Counts)) %>% 
#   filter (Country_Region == "US") %>% 
#   filter (Report_Type %in% c("Confirmed", "Deaths")) %>% 
#   ggplot(aes(x = Date,  y = log2(Counts), fill = Report_Type, color = Report_Type)) + 
#   geom_point() +
#   geom_line() +
#   ggtitle("US COVID-19 Cases")

time_series_long_joined_counts %>% 
  group_by(Country_Region, Report_Type, Date) %>% 
  summarise(Counts = sum(Counts)) %>% 
  filter (Country_Region == "Nigeria") %>% 
  filter (Report_Type %in% c("Confirmed", "Deaths")) %>% 
  ggplot(aes(x = Date,  y = log2(Counts), fill = Report_Type, color = Report_Type)) + 
  geom_point() +
  geom_line() +
  ggtitle("Nigeria COVID-19 Cases")
```


```{r}
library(maps)
library(viridis)

world <- map_data("world")
mybreaks <- c(1, 20, 100, 1000, 50000)

# ggplot() +
#   geom_polygon(data = world, aes(x=long, y = lat, group = group), fill="grey", alpha=0.3) +
#   geom_point(data=time_series_confirmed, aes(x=Long, y=Lat, size=`2/25/20`, color=`2/25/20`),stroke=F, alpha=0.7) +
#   scale_size_continuous(name="Cases", trans="log", range=c(1,7),breaks=mybreaks, labels = c("1-19", "20-99", "100-999", "1,000-49,999", "50,000+")) +
#   # scale_alpha_continuous(name="Cases", trans="log", range=c(0.1, 0.9),breaks=mybreaks) +
#   scale_color_viridis_c(option="inferno",name="Cases", trans="log",breaks=mybreaks, labels = c("1-19", "20-99", "100-999", "1,000-49,999", "50,000+")) +
#   theme_void() + 
#   guides( colour = guide_legend()) +
#   labs(caption = "") +
#   theme(
#     legend.position = "bottom",
#     text = element_text(color = "#22211d"),
#     plot.background = element_rect(fill = "#ffffff", color = NA), 
#     panel.background = element_rect(fill = "#ffffff", color = NA), 
#     legend.background = element_rect(fill = "#ffffff", color = NA)
#   )

ggplot() +
  geom_polygon(data = world, aes(x=long, y = lat, group = group), fill="grey", alpha=0.3) +
  geom_point(data=time_series_deaths, aes(x=Long, y=Lat, size=`4/25/20`, color=`4/25/20`),stroke=F, alpha=0.7) +
  scale_size_continuous(name="Deaths", trans="log", range=c(1,7),breaks=mybreaks, labels = c("1-49", "50-99", "100-999", "1,000-4,999", "5,000+")) +
  # scale_alpha_continuous(name="Cases", trans="log", range=c(0.1, 0.9),breaks=mybreaks) +
  scale_color_viridis_c(option="inferno",name="Deaths", trans="log",breaks=mybreaks, labels = c("1-49", "50-99", "100-999", "1,000-4,999", "5,000+")) +
  theme_void() + 
  guides( colour = guide_legend()) +
  labs(caption = "") +
  theme(
    legend.position = "bottom",
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#ffffff", color = NA), 
    panel.background = element_rect(fill = "#ffffff", color = NA), 
    legend.background = element_rect(fill = "#ffffff", color = NA)
  )


ggplot() +
  geom_polygon(data = world, aes(x=long, y = lat, group = group), fill="grey", alpha=0.3) +
  geom_point(data=time_series_deaths, aes(x=Long, y=Lat, size=`4/25/20`, color=`4/25/20`),stroke=F, alpha=0.7) +
  scale_size_continuous(name="Recovered", trans="log", range=c(1,7),breaks=mybreaks, labels = c("1-49", "50-99", "100-999", "1,000-4,999", "5,000+")) +
  # scale_alpha_continuous(name="Cases", trans="log", range=c(0.1, 0.9),breaks=mybreaks) +
  scale_color_viridis_c(option="inferno",name="Recovered", trans="log",breaks=mybreaks, labels = c("1-49", "50-99", "100-999", "1,000-4,999", "5,000+")) +
  theme_void() + 
  guides( colour = guide_legend()) +
  labs(caption = "") +
  theme(
    legend.position = "bottom",
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#ffffff", color = NA), 
    panel.background = element_rect(fill = "#ffffff", color = NA), 
    legend.background = element_rect(fill = "#ffffff", color = NA)
  )
```


```{r}
time_series_confirmed_long2 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region") %>%
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
               names_to = "Date", values_to = "cumulative_cases") %>%
  mutate(Date = mdy(Date) - days(1),
         Place = paste(Lat,Long,sep="_")) %>%
  group_by(Place,Date) %>%
  summarise(cumulative_cases = ifelse(sum(cumulative_cases)>0,
                                      sum(cumulative_cases),NA_real_),
            Lat = mean(Lat),
            Long = mean(Long)) %>%
  mutate(Pandemic_day = as.numeric(Date - min(Date)))


##
static <- ggplot(subset(time_series_confirmed_long2,Date %in% seq(min(Date),max(Date),14)),
                 aes(x = Long, y = Lat, size = cumulative_cases/1000)) +
  borders("world", colour = NA, fill = "grey90") +
  theme_bw() +
  geom_point(shape = 21, color='purple', fill='purple', alpha = 0.5) +
  labs(title = 'COVID-19 spread',x = '', y = '',
       size="Cases (x1000))") +
  theme(legend.position = "right") +
  coord_fixed(ratio=1)+
  facet_wrap(.~Date,ncol=1)
static

```

